param(
  [Parameter(Mandatory = $true)]
  [string]$SourceLisp
)

$ErrorActionPreference = "Stop"

function Write-Manifest {
  param([string]$ToolsDir)

  $manifest = Join-Path $ToolsDir "tools-manifest.lsp"
  $files = Get-ChildItem $ToolsDir -Filter "*.lsp" |
    Where-Object { $_.Name -ne "tools-manifest.lsp" } |
    Sort-Object Name

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add(";;; Approved LISP files loaded by CAD Subscription Tools.")
  $lines.Add(";;; Generated by admin scripts.")
  $lines.Add("")
  $lines.Add("(setq CPT_TOOL_FILES")
  $lines.Add("  '(")

  foreach ($file in $files) {
    $lines.Add("    `"$($file.Name)`"")
  }

  $lines.Add("  )")
  $lines.Add(")")

  Set-Content -Path $manifest -Value $lines -Encoding ASCII
}

$Root = Split-Path -Parent $PSScriptRoot
$ToolsDir = Join-Path $Root "pendrive\Payload\CADSubscriptionTools.bundle\Contents\Tools"

if (-not (Test-Path $SourceLisp)) {
  throw "Source LISP not found: $SourceLisp"
}

if ([IO.Path]::GetExtension($SourceLisp).ToLowerInvariant() -ne ".lsp") {
  throw "Only .lsp files are supported by this helper."
}

New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null
Copy-Item -Path $SourceLisp -Destination $ToolsDir -Force
Write-Manifest -ToolsDir $ToolsDir

Write-Host "Added LISP tool:" -ForegroundColor Green
Write-Host (Join-Path $ToolsDir (Split-Path -Leaf $SourceLisp))
Write-Host "Updated tools-manifest.lsp"
