param(
  [Parameter(Mandatory = $true)]
  [string]$ToolName
)

$ErrorActionPreference = "Stop"

function Write-Manifest {
  param([string]$ToolsDir)

  $manifest = Join-Path $ToolsDir "tools-manifest.lsp"
  $files = Get-ChildItem $ToolsDir -Filter "*.lsp" |
    Where-Object { $_.Name -ne "tools-manifest.lsp" } |
    Sort-Object Name

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add(";;; Approved LISP files loaded by CAD Subscription Tools.")
  $lines.Add(";;; Generated by admin scripts.")
  $lines.Add("")
  $lines.Add("(setq CPT_TOOL_FILES")
  $lines.Add("  '(")

  foreach ($file in $files) {
    $lines.Add("    `"$($file.Name)`"")
  }

  $lines.Add("  )")
  $lines.Add(")")

  Set-Content -Path $manifest -Value $lines -Encoding ASCII
}

$Root = Split-Path -Parent $PSScriptRoot
$ToolsDir = Join-Path $Root "pendrive\Payload\CADSubscriptionTools.bundle\Contents\Tools"
$Target = Join-Path $ToolsDir $ToolName

if (-not $ToolName.ToLowerInvariant().EndsWith(".lsp")) {
  throw "ToolName must include the .lsp extension."
}

if (Test-Path $Target) {
  Remove-Item $Target -Force
  Write-Host "Removed LISP tool:" -ForegroundColor Yellow
  Write-Host $Target
} else {
  Write-Host "Tool was not found, manifest will still be refreshed:" -ForegroundColor Yellow
  Write-Host $Target
}

Write-Manifest -ToolsDir $ToolsDir
Write-Host "Updated tools-manifest.lsp"
